### ISSUE TITLE
Help please!

### ISSUE THREAD

**Issue by bopchik** [Open-Transactions/opentxs#1454]
![image](https://user-images.githubusercontent.com/60503173/73592455-6df1c100-4503-11ea-8593-7d7c5880fd82.png)

**Comment by bopchik** [comment]
[CMakeOutput.log](https://github.com/Open-Transactions/opentxs/files/4142595/CMakeOutput.log)
[CMakeError.log](https://github.com/Open-Transactions/opentxs/files/4142596/CMakeError.log)
Log files

**Comment by justusranvier** [comment]
What are the versions of cmake and boost you are using?

**Comment by bopchik** [comment]
3.16.3 cmake and 1.67.0.2 boost

**Comment by bopchik** [comment]
And there isn`t dockerfile in opentxs

**Comment by justusranvier** [comment]
Probably the name of the cmake targets changed somewhere after boost-1.67. A newer boost version should work.

**Comment by bopchik** [comment]
Thanks. Tell me please, do libraries boost change the result? Just libraries with a version greater than 1.67.02 I did not find

**Comment by bopchik** [comment]
I meant libboost-all-dev

**Comment by justusranvier** [comment]
I know that boost-1.72 works. If your linux distribution doesn't provide a version newer than 1.67 you might need to compile it yourself.

**Comment by bopchik** [comment]
Ok, thanks

**Comment by bopchik** [comment]
I`m sorry, but i remove libboost, download 1.72 boost and install it. It install libboost 1.67.

**Comment by bopchik** [comment]
![image](https://user-images.githubusercontent.com/60503173/73598752-df059880-4544-11ea-967c-5f4cf1e97870.png)
![image](https://user-images.githubusercontent.com/60503173/73598757-f2186880-4544-11ea-8c2e-d9b32361cb7e.png)

**Comment by justusranvier** [comment]
You probably need to set BOOST_ROOT when you run cmake

https://cmake.org/cmake/help/latest/module/FindBoost.html

**Comment by bopchik** [comment]
Nothing changed. Also, it can`t find Boost:system and filesystem, but I built boost...
![image](https://user-images.githubusercontent.com/60503173/73605300-5834d800-45a5-11ea-8119-e892409ef718.png)
