### ISSUE TITLE
Account ids should be globally-unique

### ISSUE THREAD

**Issue by justusranvier** [Open-Transactions/opentxs#272]
Currently account ids are generated as random numbers by notaries. This means they can not be relied upon to be unique across notaries.

Suggested solution:

Form account ids in a manner that is verifiable as being globally unique by taking the hash of (server id, nym id, asset id, nonce), then prepend the nonce to the hash.

The size of the nonce would implicitly limit the number of accounts a nym can create for a specific asset type on a given notary. A 16 bit nonce would allow for ~66 thousand accounts per nym.

**Comment by haarts** [comment]
@justusranvier if this is still relevant, can you write a MEP for this?
