### ISSUE TITLE
smartcontract.ot is broken, needs update

### ISSUE THREAD

**Issue by themighty1** [Open-Transactions/opentxs#310]
https://github.com/Open-Transactions/opentxs/blob/develop/scripts/smartcontracts/smartcontract.ot

Many functions have been renamed, specifically those starting with stat_,
so this file need an update.

**Comment by FellowTraveler** [comment]
We will get around to this, but in the meantime, you can do this stuff in Moneychanger now, so you don't really need the script anymore.
