### ISSUE TITLE
Notary: make MessageProcessor more modular

### ISSUE THREAD

**Issue by OttoAllmendinger** [Open-Transactions/opentxs#381]
For the Auditor project, we need a Notary that is able to publish an "audit stream". The most primitive version of that is just streaming copies of all messages exchanged between client and notary. This does not satisfy the requirements for a proper audit stream, but it is something to iterate on.

One way to do this is to make the `MessageProcessor` class more modular and override certain virtual methods in a custom class `AuditableMessageProcessor`

I did that successfully a few weeks ago but not kept it up to date with `develop`. I would like to rebase that work in smaller commits and introduce these changes to the Notary. 

The actual `AuditableMessageProcessor` can just live in a fork of `opentxs-notary` and doesn't need to be merged to `develop`. 

These are the changes I made to make the MessageProcessor more modular: https://github.com/OttoAllmendinger/opentxs/commit/44cf730b1ca9b626a847b1fe1b10ebd85d857dd7. The new methods in `MessageProcessor.hpp` should tell the story. 

Please tell me what you think :)

**Comment by weissjeffm** [comment]
At first glance this bug seems no longer relevant (seems to assume auditor based on this project when it will be the new notary). Please confirm @OttoAllmendinger
