### ISSUE TITLE
MEP-2: Use ZeroMQ Curve for transport layer security

### ISSUE THREAD

**Issue by OttoAllmendinger** [Open-Transactions/opentxs#392]
**See https://github.com/monetas/protocol-docs/blob/master/content/mep/mep-002.md**

Communication between Notary and Client should be confidential and authentic.

OpenTXs currently uses a custom crypto protocol for communication between client and notary on top of plain ZeroMQ. Crypto systems are hard to implement correctly and hard to maintain and audit. We should rely on existing systems written by crypto experts as much as possible. 

One very promising candidate is the security system provided by ZeroMQ:

> The CURVE mechanism defines a mechanism for secure authentication and confidentiality for communications between a client and a server. CURVE is intended for use on public networks. The CURVE mechanism is defined by this document: http://rfc.zeromq.org/spec:25.

This significantly reduces the amount of crypto code that OT has to implement and maintain. It also makes it easier to write alternative implementations of Client or Notary.

As an additional benefit, curve provides security features that are currently not implemented in Open-Transactions, like perfect forward security (http://curvezmq.org/page:read-the-docs): 

> This handshake provides a number of protections but mainly, perfect forward security (you cannot crack data encrypted using the short term keys even if you record it, and then later get access to the permanent keys) and protection of client identity (the client permanent public key is not sent in clear-text).

These blog post explain how to use the security features provided by ZeroMQ:

* http://hintjens.com/blog:49 
* http://hintjens.com/blog:50

Necessary changes in opentxs:

* Add support for key format used in ZeroMQ curve. We should use the "Authentication" of the notary to establish the secure connection, and use the Nym's auth key to verify messages. 
* Establish a secure connection using ZeroMQ (see blog post examples)

This could co-exists in parallel to the current system. 

Note: this is completely independent from the communication between separate Nyms via the Nymbox.

**Comment by toxeus** [comment]
Finalized in #566
