### ISSUE TITLE
Update Header-License Text (Name, Email, License, Components List, PGP Signature)

### ISSUE THREAD

**Issue by lclc** [Open-Transactions/opentxs#42]
At least the signing has to be done by @FellowTraveler

**Comment by lclc** [comment]
Any progress on this regarding the license?

Would still be a problem to create an iPhone client with (LA)GPL.
Also the component list is outdated.

**Comment by FellowTraveler** [comment]
Yes, plan to have this done very soon. Just waiting on something from Johann. This is high priority.

I think we can fix the LAGPL by adding the "static linking exception" so you can create iPhone clients. Otherwise there's MPLv2.

**Comment by FellowTraveler** [comment]
License updated to MPLv2.
