### ISSUE TITLE
CI Setup jenkins jobs to work in a deterministic and parameterized way

### ISSUE THREAD

**Issue by grealish** [Open-Transactions/opentxs#450]
Re-configure jenkins jobs to be deterministic so tests can run on slaves in parrelel, make best use of parameters to pass the same hash. This should prevent race conditions where tmany PR lockup the jenkins host from compiling properly. 
Jenkins Plugin/Feature
https://wiki.jenkins-ci.org/display/JENKINS/Parameterized+Build

**Comment by weissjeffm** [comment]
I think this is basically solved on the opentxs side. The tests need to be set up to run in parallel, see https://github.com/monetas/opentxs-tests/issues/60
