### ISSUE TITLE
C#-Binding: Fix example

### ISSUE THREAD

**Issue by lclc** [Open-Transactions/opentxs#51]
Or even better: write a native binding

**Comment by lclc** [comment]
AFAIK the Windows C# dll is still not working. Either add it to the docs or remove it fully.

**Comment by haarts** [comment]
Do I need to remove the same stuff as in #52? Eg https://github.com/Open-Transactions/opentxs/tree/develop/scripts/demo/csharp or is there something else which need to be axed? 

A quick `find` revealed also:
https://github.com/Open-Transactions/opentxs/tree/develop/cmake/windll.rc.in

**Comment by lclc** [comment]
@BlueWall Is your Mono binding working with the example https://github.com/Open-Transactions/opentxs/tree/develop/scripts/demo/csharp ?

I guess this one we can remove since it's MS C#:
https://github.com/Open-Transactions/opentxs/tree/develop/scripts/demo/vscsharp

The windll.rc.in was added by Eric and it seems to be needed to build OT on Windows with MSVC.
