### ISSUE TITLE
sendcheque error

### ISSUE THREAD

**Issue by entertheabyss** [Open-Transactions/opentxs#513]
user@user:~$ opentxs sendcheque --myacct Pk37 --hisnym h0M

Welcome to Open Transactions -- version 0.93
Unable to find a server contract to use. Please use the option: --server SERVER_ID
(Where SERVER_ID is the str_Server's ID. Partial matches ARE accepted.)
Unable to find My Nym. Please use the option:   --mynym USER_ID
(Where USER_ID is the Nym's ID. Partial matches and names are accepted.)
Using as myacct: Pk37Vc2LwSX6dPg1LYbvWzgjdcLwD10I9orZkzxq76y
Using as hisnym: h0MC5moxXzI8XpOJhSRsNwRSBpRiCuiO14FWOxdeSah
Using as mypurse: K5UmgjcoaeWd1XAFbLcXBl9f9x49D8oj7vCCeEu07Gm

Usage:  sendcheque  --myacct <MY_ACCT_ID> --hisnym <RECIPIENT_NYM_ID>
Optionally: --args "memo \"one-line memo allowed here.\" amount AMOUNT"
Additionally: --args "validfor IN_SECONDS" 
This command WRITES AND SENDS the cheque.
(Use 'writecheque', not 'sendcheque', if you don't want it to be immediately SENT.)

load_public_encryption_key: Trying to load public key, assuming Nym isn't in the local wallet...
insure_enough_nums: I don't have enough transaction numbers. Grabbing more now...
Failed getting NymboxHash from Nym for server: 5E81416qGxeEY9V1wqFFUMsoD2EpOOsaMQb5K1UQB3H

=====>BEGIN Sending getTransactionNum message via ZMQ... Request number: 128
Utility::getTransactionNumbers: FYI: getTransactionNumLowLevel did send, but returned failure (0). (Re-trying...)

=====>BEGIN Sending getRequest message via ZMQ... Request number: 1
Received new request number from the server: 129. Updating Nym records...
Utility::getNymbox: Warning: Unable to retrieve recent cached copy of server-side NymboxHash from client-side nym (perhaps he's never downloaded it before?)

Utility::getNymbox: Warning: Unable to retrieve client-side NymboxHash for:
 serverID: 5E81416qGxeEY9V1wqFFUMsoD2EpOOsaMQb5K1UQB3H
 nymID: wis5MDIPxw9jedPkZVsFs2eoRRGfiYxxsw6l6SWQC8f

=====>BEGIN Sending getNymbox message via ZMQ... Request number: 129
Utility::getNymbox: Failure: this.getNymboxLowLevel returned unexpected value: 0
Utility::getAndProcessNymbox: Failure: this.getNymbox returned: -1
Utility::getTransactionNumbers: Failure: getAndProcessNymbox. Returned value: -1

=====>BEGIN Sending getRequest message via ZMQ... Request number: 1
Received new request number from the server: 130. Updating Nym records...

 SUCCESS syncronizing the request number.
Utility::getNymbox: Warning: Unable to retrieve recent cached copy of server-side NymboxHash from client-side nym (perhaps he's never downloaded it before?)

Utility::getNymbox: Warning: Unable to retrieve client-side NymboxHash for:
 serverID: 5E81416qGxeEY9V1wqFFUMsoD2EpOOsaMQb5K1UQB3H
 nymID: wis5MDIPxw9jedPkZVsFs2eoRRGfiYxxsw6l6SWQC8f

=====>BEGIN Sending getNymbox message via ZMQ... Request number: 130
Utility::getNymbox: Failure: this.getNymboxLowLevel returned unexpected value: 0
Utility::getAndProcessNymbox: Failure: this.getNymbox returned: -1

Error in refresh nym! nGetAndProcessNymbox: -1

**Comment by FellowTraveler** [comment]
Abyss, I just wanted to verify something you said on IRC:

abyss
10:33 [16:35:24] ya so i tried getting it to work
10:33 [16:37:25] but while i can run sendcheck with the old code it doesnt want to run in the new code

So you are saying it works in the old code (OT/OT) but NOT in the new code (OT/opentxs)

Correct?

@weissjeffm: Do you have a sendcheque test that works in the new code? Just curious what's going on here.

**Comment by weissjeffm** [comment]
@FellowTraveler I'll have to look and see which API calls are involved with `sendcheque` to see if I've covered them.

One thing I note is that the id's above are the old style - we switched to base58 with the `ot` prefix quite some time ago. 

I'll make sure this is covered, and report back here, but in the meantime maybe @entertheabyss can retry on the current codebase?

**Comment by FellowTraveler** [comment]
I think he has it working on the old code, but NOT working in the new code.

I know what you mean that the log above is generated by the old code, but it might just be an old log from before he got it working. That's why I asked him to confirm.

**Comment by weissjeffm** [comment]
OK, I looked at our tests, I don't think this case is covered. The tests pass cheques out-of-band. The voucher tests do call `otme.send_user_payment`, but the recipient still gets a copy out of band (the `send_user_payment` is just so the tests can cancel the voucher if necessary).

Can someone point me to the workflow for `sendcheque`? I presume it passes the cheque through the notary itself, how does the recipient deposit it?

**Comment by FellowTraveler** [comment]
If Alice does "opentxs sendcheque", her client writes a cheque and then sends it via send_user_payment to the recipient.

This causes the server to put the payment into the recipient's Nymbox.

When the recipient comes back online, usually the first thing his GUI will do is grab the latest copy of his Nymbox. (It will also perform a getAccountData for all his asset accounts, but that's not relevant here.)

As soon as the OT client API receives the updated Nymbox, it automatically removes any incoming payments and puts them into the "payments inbox" for that Nym.

At this point the incoming cheque will appear in the client GUI. (Command line tool, Moneychanger, iOS, and Android apps all do this now.)

The user can then click on the cheque and click the button "accept payment." But usually what will actually happen is, the GUIs have a built-in option to AUTOMATICALLY accept all incoming payments. 

Either way, this performs the equivalent of the command-line "opentxs acceptpayments" command. (See the OT_ME::accept_from_paymentbox function.)

In the case of a cheque, this will deposit it. This is how payments are always received in the existing clients, so I'd be surprised if it doesn't work in the new code.

**Comment by toxeus** [comment]
@entertheabyss wrote:
> user@user:~$ opentxs sendcheque --myacct Pk37 --hisnym h0M
Welcome to Open Transactions -- version 0.93

You seem to use a super-old opentxs version. The current version is `0.94.0-423-gcc0a4be`. That means we are currently 423 commits past `0.94.0`. And you are still on `0.93` which is by far more behind. Can you please try to reproduce with a recent opentxs version?

**Comment by entertheabyss** [comment]
i appologize for the delayed response. 

i have installed the current version of opentxs following the standard debian-ubuntu installation doc. however the otserver executable did not appear to compile. not sure what to do.

**Comment by weissjeffm** [comment]
There server source is now in opentxs-notary repo, and it will compile a binary of the same name.

**Comment by entertheabyss** [comment]
ok i got the server and the client running but they cant seem to reach each other
when i try to run: it just pints the following and doesnt do anything

user@user:~$ opentxs refreshnym --server otxU1 --mynym 1st


Welcome to Open Transactions -- version 0.94.0-457-g1ebdb13
Using server: otxU1aov321n3tLSMNd6y5obvCExW3tp4csc
Using mynym: otxW7ng9bi2cWWYhEg4vTXDR8beG3x5LpXDL
OTPaths::ConfirmCreateFolder: Unable To Confirm Created Directory /home/user/.ot/client_data/nyms/otxU1aov321n3tLSMNd6y5obvCExW3tp4csc/sent/otxW7ng9bi2cWWYhEg4vTXDR8beG3x5LpXDL/.
BuildFolderPath: Made new folder: /home/user/.ot/client_data/nyms/otxU1aov321n3tLSMNd6y5obvCExW3tp4csc/sent/otxW7ng9bi2cWWYhEg4vTXDR8beG3x5LpXDL/

=====>BEGIN Sending getRequestNumber message via ZMQ... Request number: 1

**Comment by weissjeffm** [comment]
This hanging is indicative of an unreachable server.

The client has to have the server contract installed, so that it knows where to contact the server - in this case, `localhost`.  Either the server isn't running or reachable, or the contract is specifying some other host or port.

**Comment by weissjeffm** [comment]
@entertheabyss please reopen if you're able to reproduce on the latest.
