### ISSUE TITLE
create monetas PPA

### ISSUE THREAD

**Issue by mhamrle** [Open-Transactions/opentxs#518]
We need backported packages for trusty. Now my personal ppa is used but it makes sense to have PPA that is accessible by anyone from Monetas.

**Comment by mhamrle** [comment]
monetas PPA created https://launchpad.net/~monetas/+archive/ubuntu/opentxs/ and moved all packages needed for opentxs

Let me know who wants to add into monetas team.

Next step is to modify all dockerfiles to use monetas ppa instead of mine.

**Comment by toxeus** [comment]
https://github.com/Open-Transactions/docker/pull/4

**Comment by toxeus** [comment]
Thanks for the good job @mhamrle
