### ISSUE TITLE
PHP-Binding: Fix example

### ISSUE THREAD

**Issue by lclc** [Open-Transactions/opentxs#52]
Or even better: write a native binding

**Comment by lclc** [comment]
I'm ok with closing this if we say no PHP bindings anymore (which I support, since OT stuff should always happen on client side), but then please make a PR to delete this folder: https://github.com/Open-Transactions/opentxs/tree/develop/scripts/demo/php

**Comment by haarts** [comment]
Makes sense! Will do.
