### ISSUE TITLE
Rename credentialList

### ISSUE THREAD

**Issue by toxeus** [Open-Transactions/opentxs#537]
Rename
* ~~`credentials` to `credentialIDs`~~
* ~~`crednetialList` to `credientals`~~
* `credentialList` to `credentialIDs`

That is just a bad and misleading name. 

Example targeted code: https://github.com/Open-Transactions/opentxs/blob/develop/src/core/Contract.cpp#L2465-2466

**Comment by teknico** [comment]
That's a good idea, :+1: .

I would also change the confusing "MASTER KEY CREDENTIAL" in the headers.

**Comment by toxeus** [comment]
@teknico I think that one is related to the signature

**Comment by mhamrle** [comment]
:+1:

**Comment by benma** [comment]
:+1:

**Comment by mhamrle** [comment]
@toxeus could you make a MEP for the renames

**Comment by toxeus** [comment]
@mhamrle done https://github.com/monetas/protocol-docs/pull/173

Although, it's a little bit of an overkill ;)

**Comment by toxeus** [comment]
Closed by https://github.com/Open-Transactions/opentxs/pull/539
