### ISSUE TITLE
Remove unused git modules

### ISSUE THREAD

**Issue by lclc** [Open-Transactions/opentxs#540]
in https://github.com/Open-Transactions/opentxs/tree/develop/deps we have the following git modules that are not used:

bitcoin-crypto
secp256k1

Does anybody plan to use those?
I expect not since we use libsodium now for signing.

Then we could also remove the following repos:
https://github.com/Open-Transactions/bitcoin-crypto
https://github.com/Open-Transactions/secp256k1
https://github.com/Open-Transactions/cryptopp

Any objections?

**Comment by lclc** [comment]
Also we should probably fork https://github.com/benma/bitcoin-core-base58 from Benma into the Open-Transactions organisations, so we don't rely on his goodwill to not delete that repo ;)

**Comment by toxeus** [comment]
Open-Transactions suffers a lot from too many repos. Thanks for finding out what can be effortless removed :+1:

**Comment by toxeus** [comment]
@lclc wrote:
> I expect not since we use libsodium now for signing.

Not yet. It's still RSA from openssl.
