### ISSUE TITLE
Temporary test branch "no-envelope"

### ISSUE THREAD

**Issue by OttoAllmendinger** [Open-Transactions/opentxs#551]
In order to simplify notary testing, we need a branch of opentxs that does not use OTEnvelope, and only uses CurveZMQ with the hard-coded static key. 

That branch should not be used in production, only for testing purposes.

**Comment by benma** [comment]
There you go:

https://github.com/Open-Transactions/opentxs/tree/no-envelope

Thanks @haarts.
