### ISSUE TITLE
Use notary provider contract "transportKey" for CurveZMQ instead of hard-coded key

### ISSUE THREAD

**Issue by OttoAllmendinger** [Open-Transactions/opentxs#553]
~~* Use the Notary's "A" key for authenticating the notary and establishing a confidential transport (instead of the hard-coded key)~~
~~* Remove "A" signature from the notary response message, since the transport layer is already authenticated.~~

**Comment by toxeus** [comment]
* add support to read the new `transportKey` field in the notary provider contract
* use the read `transportKey` [here](https://github.com/Open-Transactions/opentxs/blob/develop/src/client/OTServerConnection.cpp#L170-L171)
* add support to write a notary provider contract that contains the `transportKey` field using the `opentxs newserver` CLI command

**Comment by toxeus** [comment]
Finalized in #566 and #574
