### ISSUE TITLE
opentxs sendvoucher cli command is asserting in opentransactions.cpp line 4559

### ISSUE THREAD

**Issue by ghost** [Open-Transactions/opentxs#559]
Using opentxs library 0.94.0-505-g3179217 with opentxs-server 0.94.0-15-gb93ac19 under Ubuntu 14.04 LTS, the opentxs sendvoucher cli command is crashing with an assert in opentransactions.cpp line 4559 in the GetOrLoadNym function.

This bug appeared after creating a new opentxs-notary on the HP Cloud, creating and issuing an asset, creating a user account for that asset type, and then calling:

opentxs sendvoucher --myacct 'CHF Issuer' --hisnym "Barry's CHF" --amount 5000.00 --memo 'test issuer sendvoucher'

The stack trace follows:

opentxs sendvoucher --myacct 'CHF
Issuer' --hisnym "Barry's CHF" --amount 5000.00 --memo 'test issuer
sendvoucher'

Welcome to Open Transactions -- version 0.94.0-505-g3179217

GetMasterPassword: Please enter your password.

Passphrase request for: "Loading private key from credential."
(OT) passphrase:

Using myacct: otxCMZ6mB9emwpbrKpLetKW33uoxBcbVRTT3
Using hisnym: Barry's CHF
Using myacct: otxCMZ6mB9emwpbrKpLetKW33uoxBcbVRTT3
Using hisnym: Barry's CHF

load_public_encryption_key: Trying to load public key, assuming Nym
isn't in the local wallet...

OT_ASSERT in
/home/barry/dev/Monetas6/opentxs/src/client/OpenTransactions.cpp at
line 4559
stack trace:
  /usr/local/lib/x86_64-linux-gnu/libopentxs-core.so.0 :
opentxs::Log::logAssert(char const_, unsigned long, char const_)+0xfd
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::OT_API::GetOrLoadNym(opentxs::Identifier const&, bool, char
const_, opentxs::OTPasswordData const_) const+0x152
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::OTAPI_Exec::LoadPubkey_Encryption(std::string const&) const+0xcb
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::OTAPI_Wrap::LoadPubkey_Encryption(std::string const&)+0x1f
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::MadeEasy::load_public_encryption_key(std::string const&)+0x48
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::MadeEasy::load_or_retrieve_encrypt_key(std::string const&,
std::string const&, std::string const&)+0x35
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::CmdWithdrawVoucher::run(std::string, std::string,
std::string, std::string, std::string&)+0x13f
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::CmdSendVoucher::run(std::string, std::string, std::string,
std::string)+0x110
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::CmdSendVoucher::runWithOptions()+0xde
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::CmdBase::run(std::map<std::string, std::string,
std::less<std::string>, std::allocator<std::pair<std::string const,
std::string> > > const&)+0xc7
  opentxs : opentxs::Opentxs::runCommand(opentxs::CmdBase&)+0x35f
  opentxs : opentxs::Opentxs::processCommand(AnyOption&)+0x7da
  opentxs : opentxs::Opentxs::run(int, char**)+0x132
  opentxs : main()+0x27
  /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xf5
  opentxs() [0x408997]
stack trace:
  /usr/local/lib/x86_64-linux-gnu/libopentxs-core.so.0 :
opentxs::ot_terminate()+0x117
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : ()+0x5eca6
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : ()+0x5ecf1
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::OT_API::GetOrLoadNym(opentxs::Identifier const&, bool, char
const_, opentxs::OTPasswordData const_) const+0x157
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::OTAPI_Exec::LoadPubkey_Encryption(std::string const&) const+0xcb
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::OTAPI_Wrap::LoadPubkey_Encryption(std::string const&)+0x1f
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::MadeEasy::load_public_encryption_key(std::string const&)+0x48
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::MadeEasy::load_or_retrieve_encrypt_key(std::string const&,
std::string const&, std::string const&)+0x35
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::CmdWithdrawVoucher::run(std::string, std::string,
std::string, std::string, std::string&)+0x13f
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::CmdSendVoucher::run(std::string, std::string, std::string,
std::string)+0x110
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::CmdSendVoucher::runWithOptions()+0xde
  /usr/local/lib/x86_64-linux-gnu/libopentxs-client.so.0 :
opentxs::CmdBase::run(std::map<std::string, std::string,
std::less<std::string>, std::allocator<std::pair<std::string const,
std::string> > > const&)+0xc7
  opentxs : opentxs::Opentxs::runCommand(opentxs::CmdBase&)+0x35f
  opentxs : opentxs::Opentxs::processCommand(AnyOption&)+0x7da
  opentxs : opentxs::Opentxs::run(int, char**)+0x132
  opentxs : main()+0x27
  /lib/x86_64-linux-gnu/libc.so.6 : __libc_start_main()+0xf5
  opentxs() [0x408997]
Aborted (core dumped)

**Comment by ibrokeit** [comment]
I just noticed, I mistakenly used my CHF account nym for 'hisnym' instead of the client user nym. Nonetheless, using an incorrect parameter should not cause opentxs to crash.

**Comment by benma** [comment]
Patches are welcome :)

**Comment by weissjeffm** [comment]
This is a relatively hard-to-hit bug and probably won't be an issue in the android client, but since it's a crash I'll tentatively triage this for v1
