### ISSUE TITLE
Rename NymFile to NymData

### ISSUE THREAD

**Issue by haarts** [Open-Transactions/opentxs#560]
In the RegisterNymResponse the part which is always known as NymData now all of the sudden is called NymFile. That's unnecessarily confusing.

**Comment by benma** [comment]
https://github.com/Open-Transactions/opentxs/issues/423

OTuser was once renamed to nymData. Need to check if nymFile indeed refers to the same thing.

**Comment by OttoAllmendinger** [comment]
See https://github.com/monetas/protocol-docs/issues/183

The correct name for the element would be something like `<resyncData>`, any overlap with `<nymData>` used in the request is accidental. The current name is just an implementation artifact.
