### ISSUE TITLE
Currency parsing and formatting is broken in several ways

### ISSUE THREAD

**Issue by weissjeffm** [Open-Transactions/opentxs#569]
Here are the broken testcases for formatting:

```
# asset attributes, number to format, expected output
{'factor': '1', 'decimal_power': '2, 'symbol': "BTC"}, -1, "BTC -1"  # actual output is "-BTC 1", does not work properly with negative amounts
{'factor': '16', 'decimal_power': '2', 'symbol': "£"}, 49, "£ 3.0625"  # actual output is "£ 3.1", does not work properly with non decimal units like 16 ounces per pound.
```

Broken testcases for parsing:

```
# asset attributes, string to parse, expected output
{'decimal_power': '2', 'factor': '100', 'symbol': '$'}, "$ 1,234,567.89", 123456789  # actual output is 123456700 
{'decimal_power': '6', 'factor': '1000000', 'symbol': "BTC"}, "BTC 123.456789", 123456789  # actual output is 123000000
```

An important question is, what do we do when parsing, when the amount given doesn't come out to an even number of units?

For example, `£ 3.06`, at 16 ounces per pound, isn't exactly 49 ounces, it's `48.96`. But we can't use that because we're dealing with integer ounces. I don't think we can just round up either.

This is easier to handle with decimal factors like 10 or 100, where you can just limit the user's input field to a certain number of digits. But it does not work with factors like 16.

**Comment by mhamrle** [comment]
I agree to use only decimal powers. We have [check](https://github.com/monetas/design-docs/pull/6/files#diff-e95245649975b94063f6709854256ee9R62) for it.
