### ISSUE TITLE
MSVC 2013 build fails re gmtime_r, timegm, int8_t and more

### ISSUE THREAD

**Issue by rfree2** [Open-Transactions/opentxs#572]
Using MSVC Express 2013 to compile opentxs commit f6f58e11b0bb940e5b126cc594af89a36b0842b4
but compilation fails with various errors.

EDIT: checked with latest 3204ab5fe31afbb2b6b4456ef8dc860b5658884e - same problem

I could fix this errors, but first is MSVC Express 2013 supposed to work and am I doing the Windows build correctly? (Usually working on Linux so could be my mistake).

Was following instructions from https://github.com/Open-Transactions/opentxs/blob/develop/docs/INSTALL-Windows.txt ; It was a bit unclear how to compile libprotobuf - or which version/compiler is ok.

The dependencies were downloaded or builded from sources in msys, eg.:
libprotobuf - builded it in msys, from sources (using gcc)
zeromq, openssl, zlib - installed with the installer of that libarary downloaded from their homepage afair.

The gcc used is:

``` text
win@win-Komputer MSYS ~ 
$ gcc -v

Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/4.9.2/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-4.9.2/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --with-gxx-include-dir=/mingw64/include/c++/4.9.2 --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-cloog-backend=isl --enable-version-specific-runtime-libs --disable-cloog-version-check --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-cloog=/mingw64 --with-pkgversion='Rev4, Built by MSYS2 project' --with-bugurl=http://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 4.9.2 (Rev4, Built by MSYS2 project)
```

Then the opentxs source was downloaded (git check out).
Used cmake in opnetxs sources:
mkdir build
cd build
cmake -D PROTOBUF_INCLUDE_DIR="C:\msys64\usr\i686-w64-mingw32\include\google\protobuf" -D PROTOBUF_LIBRARY="C:\msys64\usr\i686-w64-mingw32\lib" ..

It succeeded.

Later, opened the project file and builded it: MSVC: Build => Build Solution

It shown compilation errors including for example:

``` text

StringUtils.cpp

std::string formatTimestamp(time64_t tt)
{
    struct tm tm;
    time_t t = tt;
    char buf[255];

    strftime(buf, sizeof(buf), "%FT%T", gmtime_r(&t, &tm));
    return std::string(buf);
}

Error   44  error C3861: 'gmtime_r': identifier not found   C:\OT\opentxs\src\core\util\StringUtils.cpp 187 1   opentxs-core


**********************************************************
time64_t parseTimestamp(std::string extendedTimeString)
{
    struct tm tm;
    if (!strptime(extendedTimeString.c_str(), "%Y-%m-%dT%H:%M:%S", &tm)) {
        return 0;
    }

Error   45  error C3861: 'strptime': identifier not found   C:\OT\opentxs\src\core\util\StringUtils.cpp 199 1   opentxs-core

**********************************************************
#ifdef ANDROID
    time64_t t = timegm64(&tm);
#else
    time_t t = timegm(&tm);
#endif
    if (t == -1) return 0;
    return t;
}

Error   46  error C3861: 'timegm': identifier not found C:\OT\opentxs\src\core\util\StringUtils.cpp 206 1   opentxs-core
**********************************************************
#ifndef Z_SOLO
#  if defined(Z_HAVE_UNISTD_H) || defined(_LARGEFILE64_SOURCE)
#    include <unistd.h>         /* for SEEK_*, off_t, and _LFS64_LARGEFILE */
#    ifdef VMS
#      include <unixio.h>       /* for off_t */
#    endif
#    ifndef z_off_t
#      define z_off_t off_t
#    endif
#  endif
#endif

Error   47  error C1083: Cannot open include file: 'unistd.h': No such file or directory    c:\msys64\mingw64\include\zconf.h   452 1   opentxs-core
**********************************************************
// static
void OTLog::SetupSignalHandler()
{
    static int32_t nCount = 0;

    if (0 == nCount) {
        ++nCount;
        SetUnhandledExceptionFilter(
            (LPTOP_LEVEL_EXCEPTION_FILTER)Win32FaultHandler);
    }
}

Error   50  error C2653: 'OTLog' : is not a class or namespace name C:\OT\opentxs\src\core\Log.cpp  935 1   opentxs-core
**********************************************************
Error   55  error LNK1104: cannot open file '..\..\lib\Debug\opentxs-core.lib'  C:\OT\opentxs\build\src\cash\LINK   opentxs-cash

**********************************************************
Error   56  error C2371: 'int8_t' : redefinition; different basic types c:\ot\opentxs\deps\czmq\include\czmq_prelude.h  437 1   opentxs-server


```

Is it something that should be fixed in source code (I can do it no problem) - or is this toolchain not supported?

**Comment by rfree2** [comment]
Fix for this is almost ready (now down to linking errors)

**Comment by yamamushi** [comment]
@rfree2 How is your progress on resolving the linking errors? Specifically, the int8_t redefinition errors.

**Comment by FellowTraveler** [comment]
Problem: error C3861: 'timegm': identifier not found 
Solution: #define timegm _mkgmtime
Another solution: http://trac.rtmpd.com/browser/trunk/sources/common/src/platform/win32/timegm.cpp?rev=2
--------------------
Problem: error C3861: 'strptime': identifier not found 
Solution: http://trac.rtmpd.com/browser/trunk/sources/common/src/platform/win32/strptime.cpp?rev=2&order=name
---------------------
Problem: error C3861: 'gmtime_r': identifier not found 
Solution: 
std::string formatTimestamp(time64_t tt)
{
    char buf[255]="";
    struct tm tm;
    // -------------
#if defined(_WIN32) || defined(_WIN64)
    if (0 ==_gmtime64_s(&tm, &tt))
        strftime(buf, sizeof(buf), "%FT%T", &tm);
#else
    time_t t = tt; // Todo why go backwards here? Prefer time64_t.
    strftime(buf, sizeof(buf), "%FT%T", gmtime_r(&t, &tm));
#endif
    return std::string(buf);
}

**Comment by FellowTraveler** [comment]
For the OTLog issue, look at the UNIX sig handler and see what name it uses to refer to OTLog. 

For the ZMQ issues -- those sound ZMQ specific. Did anyone make any progress on this? Surely ZMQ must work on Windows!

**Comment by yamamushi** [comment]
@rfree2 has a repository on his profile containing all of his build notes, and using those I was able to move past the issues he reported above. 

However there remains the issues with building CZMQ, which appears to be suffering from a conflict in typedef's for uint8_t. I believe that by using the instructions here, http://lists.zeromq.org/pipermail/zeromq-dev/2015-January/028007.html , that those can also be resolved. A more permanent solution needs to be implemented by the CZMQ team going forward though.
