### ISSUE TITLE
Fix ackNums leaking on client

### ISSUE THREAD

**Issue by mhamrle** [Open-Transactions/opentxs#582]
ackNum lifecycle:
Client sends request to notary, notary generates response and for some message types drops response into nymbox.
Client receives response and adds number into ackNums.

Client sends his ackNums to the notary in next request. The notary receives client's ackNums and compare with his own ackNums. If some number is missing in clients ackNums notary, notary removes it from its ackNums. If some number is missing in notary's ackNums, notary tries to remove corresponding response from nymbox and if successful adds the number into notary's ackNums.

Notary sends in next response notary's ackNums to the client.
Client receives notary's ackNums and for each number from notary's list remove the same number from client's list.

Client sends in next request client's list to notary. Notary compares lists and remove numbers from notary's ackNums that are not in client's ackNums.

There is problem in this algorithm that notary refuses to add number into his ackNums if removing reply from nymbox fails (and it means the number is never removed from client's ackNums). Not every message type drops reply into nymbox so it means that the number stays in client's ackNums forever.

This is fixed by limiting number of ackNums to 100 [here](https://github.com/Open-Transactions/opentxs/blob/17d9d25b95f93fbaf4d46c93baefd8a7fa3a748c/src/core/Nym.cpp#L2598). It should be fixed by removing the number from notary's even if removing reply from nymbox fails [here](https://github.com/Open-Transactions/opentxs/blob/17d9d25b95f93fbaf4d46c93baefd8a7fa3a748c/src/server/UserCommandProcessor.cpp#L973).

I do not want to implement this buggy algorithm in gotary. Chris, do you see any problem if we remove

**Comment by FellowTraveler** [comment]
Fixed in https://github.com/Open-Transactions/opentxs/pull/605

This process is for network optimization. Many extra messages would go down the pipe without it.
