### ISSUE TITLE
Can not use custom server (contract) from other user

### ISSUE THREAD

**Issue by rfree2** [Open-Transactions/opentxs#585]
1. Created own server (contract)
2. Started server from unix system user A
3. Exported the server contract from user A, imported in on a new, clean unix system user B who had no ~/.ot/
4. Using server works from unix user A (ping and other commands)
5. Using server fails from unix user B. It usually crashes or sometimes hangs.

If we skip step 1 and do the same things on the default example server contract, then all works fine.

Perhaps we made a mistake when creating our OT sever, but then it would be still lack of proper asserts in handling of such invalid user supplied data.

Using opentxs-cli command line interface to OT, in version:
https://github.com/Avvys/opentxs-cli/commit/caee514f56d533cac09e4c8a99aa028066b09629

Video demonstration of the bug is on:
https://vimeo.com/123841191 (uploads now)
and youtube: https://www.youtube.com/watch?v=MuFktvMcpwk

**Comment by rfree2** [comment]
Some text data showing the bug:

ot-cli@laboratory ~/opentxs-cli(develop=) $ uname -a
Linux laboratory 3.2.66-grsec-mempo.desk.0.2.106 #1 SMP PREEMPT Fri Feb 6 08:34:44 UTC 2015 x86_64 GNU/Linux
ot-cli@laboratory ~/opentxs-cli(develop=) $ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy

ot-cli@laboratory ~/opentxs-cli(develop=) $ ./run.sh gdb
ot command> ot server ping Tigusoft test


Welcome to Open Transactions -- version 0.94.0-528-g3204ab5
[New Thread 0x3fff39ad700 (LWP 3473)]
Checking connection (Tigusoft) for nym: test
[New Thread 0x3fff31ac700 (LWP 3475)]
[New Thread 0x3fff29ab700 (LWP 3476)]

Program received signal SIGSEGV, Segmentation fault.
zmq::options_t::setsockopt(int, void const*, unsigned long) () at src/options.cpp:427
427	src/options.cpp: No such file or directory.

Thread 4 (Thread 0x3fff29ab700 (LWP 3476)):
#0  clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:84
#1  0x000003fff5448a80 in ?? () at pthread_create.c:217 from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x000003fff29ab700 in ?? ()
#3  0x0000000000000000 in ?? ()

Thread 3 (Thread 0x3fff31ac700 (LWP 3475)):
#0  0x000003fff5739fb3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:82
#1  0x000003fff3c1f25f in zmq::epoll_t::loop() () at src/epoll.cpp:145
#2  0x000003fff3c48d23 in thread_routine(void*) () from /home/ot-cli/.local/lib/libzmq.so.4
#3  0x000003fff5448b50 in start_thread (arg=<optimized out>) at pthread_create.c:304
#4  0x000003fff573995d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#5  0x0000000000000000 in ?? ()
---Type <return> to continue, or q <return> to quit---

Thread 2 (Thread 0x3fff39ad700 (LWP 3473)):
#0  0x000003fff570948d in nanosleep () at ../sysdeps/unix/syscall-template.S:82
#1  0x000003fff662ae4f in opentxs::OTCachedKey::ThreadTimeout(void*) () from /home/ot-cli/.local/lib/libopentxs-core.so.0
#2  0x000003fff5f37400 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x000003fff5448b50 in start_thread (arg=<optimized out>) at pthread_create.c:304
#4  0x000003fff573995d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#5  0x0000000000000000 in ?? ()

Thread 1 (Thread 0x3fff7fca720 (LWP 3469)):
#0  zmq::options_t::setsockopt(int, void const*, unsigned long) () at src/options.cpp:427
#1  0x000003fff3c3951c in zmq::socket_base_t::setsockopt(int, void const*, unsigned long) () at src/socket_base.cpp:320
#2  0x000003fff7459876 in opentxs::OTServerConnection::OTServerConnection(opentxs::OTClient*, std::string const&, unsigned char const*) () from /home/ot-cli/.local/lib/libopentxs-client.so.0
#3  0x000003fff7422660 in opentxs::OTClient::ProcessMessageOut(opentxs::OTServerContract*, opentxs::Nym*, opentxs::Message const&) () from /home/ot-cli/.local/lib/libopentxs-client.so.0
#4  0x000003fff7269498 in opentxs::OT_API::pingNotary(opentxs::Identifier const&, opentxs::Identifier const&) const () from /home/ot-cli/.local/lib/libopentxs-client.so.0
#5  0x000003fff741a40a in opentxs::OTAPI_Exec::pingNotary(std::string const&, std::string const&) const () from /home/ot-cli/.local/lib/libopentxs-client.so.0
#6  0x00000000005f9149 in nOT::nUse::cUseOT::ServerPing(std::string const&, std::string const&, bool) ()
#7  0x0000000000789ae4 in std::_Function_handler<int (std::shared_ptr<nOT::nNewcli::cCmdData>, nOT::nUse::cUseOT&), nOT::nNewcli::cCmdParser::Init()::$_170>::_M_invoke(std::_Any_data const&, std::shared_ptr<nOT::nNewcli::cCmdData>, nOT::nUse::cUseOT&) ()
#8  0x000000000072607a in std::function<int (std::shared_ptr<nOT::nNewcli::cCmdData>, nOT::nUse::cUseOT&)>::operator()(std::shared_ptr<nOT::nNewcli::cCmdData>, nOT::nUse::cUseOT&) const ()
#9  0x000000000071514b in nOT::nNewcli::cCmdExecutable::operator()(std::shared_ptr<nOT::nNewcli::cCmdData>, nOT::nUse::cUseOT&) ()
#10 0x00000000007137f3 in nOT::nNewcli::cCmdProcessing::_UseExecute() ()
#11 0x000000000070e85c in nOT::nNewcli::cCmdProcessing::UseExecute() ()
#12 0x00000000004522ce in nOT::nOTHint::cInteractiveShell::Execute(std::string) ()
#13 0x000000000048f137 in nOT::nOTHint::cInteractiveShell::_RunEditline(std::shared_ptr<nOT::nUse::cUseOT>) ()
#14 0x000000000048c33d in nOT::nOTHint::cInteractiveShell::RunEditline(std::shared_ptr<nOT::nUse::cUseOT>) ()
#15 0x00000000004335e2 in nOT::nNewcli::cOTCli::_Run(std::vector<std::string, std::allocator<std::string> >) ()
---Type <return> to continue, or q <return> to quit---
#16 0x00000000004254f4 in nOT::nNewcli::cOTCli::Run(std::vector<std::string, std::allocator<std::string> >) ()
#17 0x000000000041cb0b in main ()
A debugging session is active.

	Inferior 1 [process 3469] will be killed.







ot-cli@laboratory ~/opentxs-cli(develop=) $ ./run.sh gdb
server not found!
GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/ot-cli/opentxs-cli/build/bin/otx...(no debugging symbols found)...done.
Starting program: /home/ot-cli/opentxs-cli/build/bin/otx +normal +debugfile --complete-shell
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

For help type: ot help
ot command> ot nym new test2 --register


Welcome to Open Transactions -- version 0.94.0-528-g3204ab5
[New Thread 0x3fff39ad700 (LWP 3590)]
..........................++++++
........++++++
...................................++++++
.................++++++
.................................++++++
.....++++++
BuildFilePath: Made new folder: /home/ot-cli/.ot/client_data/addressbook/BuildFolderPath: Made new folder: /home/ot-cli/.ot/client_data/credentials/otxTRFoykKdpzQUXqHuzk8EaEKJtiz4p9acr/
...............++++++
............++++++
.........++++++
.....++++++
...............++++++
.....................................++++++
Nym test2(otxTRFoykKdpzQUXqHuzk8EaEKJtiz4p9acr) created successfully.
[New Thread 0x3fff31ac700 (LWP 3594)]
[New Thread 0x3fff29ab700 (LWP 3595)]

Program received signal SIGSEGV, Segmentation fault.
zmq::options_t::setsockopt(int, void const*, unsigned long) () at src/options.cpp:427
427	src/options.cpp: No such file or directory.

Thread 4 (Thread 0x3fff29ab700 (LWP 3595)):
#0  __lll_lock_wait_private () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:97
#1  0x000003fff5449b73 in _L_lock_2504 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x000003fff5448d21 in start_thread (arg=<optimized out>) at pthread_create.c:295
#3  0x000003fff573995d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#4  0x0000000000000000 in ?? ()

Thread 3 (Thread 0x3fff31ac700 (LWP 3594)):
#0  0x000003fff5739fb3 in epoll_wait () at ../sysdeps/unix/syscall-template.S:82
#1  0x000003fff3c1f25f in zmq::epoll_t::loop() () at src/epoll.cpp:145
#2  0x000003fff3c48d23 in thread_routine(void*) () from /home/ot-cli/.local/lib/libzmq.so.4
#3  0x000003fff5448b50 in start_thread (arg=<optimized out>) at pthread_create.c:304
#4  0x000003fff573995d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
---Type <return> to continue, or q <return> to quit---
#5  0x0000000000000000 in ?? ()

Thread 2 (Thread 0x3fff39ad700 (LWP 3590)):
#0  0x000003fff570948d in nanosleep () at ../sysdeps/unix/syscall-template.S:82
#1  0x000003fff662ae4f in opentxs::OTCachedKey::ThreadTimeout(void*) () from /home/ot-cli/.local/lib/libopentxs-core.so.0
#2  0x000003fff5f37400 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x000003fff5448b50 in start_thread (arg=<optimized out>) at pthread_create.c:304
#4  0x000003fff573995d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#5  0x0000000000000000 in ?? ()

Thread 1 (Thread 0x3fff7fca720 (LWP 3570)):
#0  zmq::options_t::setsockopt(int, void const*, unsigned long) () at src/options.cpp:427
#1  0x000003fff3c3951c in zmq::socket_base_t::setsockopt(int, void const*, unsigned long) () at src/socket_base.cpp:320
#2  0x000003fff7459876 in opentxs::OTServerConnection::OTServerConnection(opentxs::OTClient*, std::string const&, unsigned char const*) () from /home/ot-cli/.local/lib/libopentxs-client.so.0
#3  0x000003fff7422660 in opentxs::OTClient::ProcessMessageOut(opentxs::OTServerContract*, opentxs::Nym*, opentxs::Message const&) () from /home/ot-cli/.local/lib/libopentxs-client.so.0
#4  0x000003fff726925b in opentxs::OT_API::registerNym(opentxs::Identifier const&, opentxs::Identifier const&) const () from /home/ot-cli/.local/lib/libopentxs-client.so.0
#5  0x000003fff741a4fa in opentxs::OTAPI_Exec::registerNym(std::string const&, std::string const&) const () from /home/ot-cli/.local/lib/libopentxs-client.so.0
#6  0x000003fff73db676 in OTAPI_Func::SendRequestLowLevel(OTAPI_Func&, std::string const&) const () from /home/ot-cli/.local/lib/libopentxs-client.so.0
#7  0x000003fff73dbeea in OTAPI_Func::SendRequestOnce(OTAPI_Func&, std::string const&, bool, bool, bool&) const () from /home/ot-cli/.local/lib/libopentxs-client.so.0
#8  0x000003fff73dc6c3 in OTAPI_Func::SendRequest(OTAPI_Func&, std::string const&) const () from /home/ot-cli/.local/lib/libopentxs-client.so.0
#9  0x000003fff7272a54 in opentxs::OT_ME::register_nym(std::string const&, std::string const&) const () from /home/ot-cli/.local/lib/libopentxs-client.so.0
#10 0x0000000000586b2a in nOT::nUse::cUseOT::NymRegister(std::string const&, std::string const&, bool, bool) ()
#11 0x000000000057fc3f in nOT::nUse::cUseOT::NymCreate(std::string const&, bool, bool) ()
#12 0x00000000007917e5 in std::_Function_handler<int (std::shared_ptr<nOT::nNewcli::cCmdData>, nOT::nUse::cUseOT&), nOT::nNewcli::cCmdParser::Init()::$_147>::_M_invoke(std::_Any_data const&, std::shared_ptr<nOT::nNewcli::cCmdData>, nOT::nUse::cUseOT&) ()
#13 0x000000000072607a in std::function<int (std::shared_ptr<nOT::nNewcli::cCmdData>, nOT::nUse::cUseOT&)>::operator()(std::shared_ptr<nOT::nNewcli::cCmdData>, nOT::nUse::cUseOT&) const ()
#14 0x000000000071514b in nOT::nNewcli::cCmdExecutable::operator()(std::shared_ptr<nOT::nNewcli::cCmdData>, nOT::nUse::cUseOT&) ()
---Type <return> to continue, or q <return> to quit---
#15 0x00000000007137f3 in nOT::nNewcli::cCmdProcessing::_UseExecute() ()
#16 0x000000000070e85c in nOT::nNewcli::cCmdProcessing::UseExecute() ()
#17 0x00000000004522ce in nOT::nOTHint::cInteractiveShell::Execute(std::string) ()
#18 0x000000000048f137 in nOT::nOTHint::cInteractiveShell::_RunEditline(std::shared_ptr<nOT::nUse::cUseOT>) ()
#19 0x000000000048c33d in nOT::nOTHint::cInteractiveShell::RunEditline(std::shared_ptr<nOT::nUse::cUseOT>) ()
#20 0x00000000004335e2 in nOT::nNewcli::cOTCli::_Run(std::vector<std::string, std::allocator<std::string> >) ()
#21 0x00000000004254f4 in nOT::nNewcli::cOTCli::Run(std::vector<std::string, std::allocator<std::string> >) ()
#22 0x000000000041cb0b in main ()
A debugging session is active.

	Inferior 1 [process 3570] will be killed.

**Comment by rfree2** [comment]
Added video showing how we created the contract of this server, that exhibits the problem:

https://www.youtube.com/watch?v=qfb5nbUs9y4

(you can skip middle half of video - just entropy generation)

**Comment by rfree2** [comment]
The XML data of the contracts used to create our example server shown in video can be downloaded here:

https://github.com/rfree2/opentransactions-misc/tree/master/bug/opentxs_issues_585

**Comment by FellowTraveler** [comment]
This issue needs to be moved to the opentxs-cli project issues list.

opentxs comes with a built-in command-line client ("opentxs") I would be curious to know if this problem can be reproduced with that client instead of this one. It could be that the issue belongs here after all, but we don't know that yet. When I get time I will look into getting an OT server up in a VM here and test it out.

**Comment by FellowTraveler** [comment]
One more thing, if you ARE able to reproduce it using *opentxs* instead of *opentxs-cli* the next thing you should do is try removing all the condition tags and see if it still happens. There might be a character in one of those tags that is screwing with the parser.
Best solution for this is to base64-encode all human-readable tags instead of leaving them in the clear. That way they cannot affect the parsing code.
