### ISSUE TITLE
Ubuntu build error

### ISSUE THREAD

**Issue by brenoc** [Open-Transactions/opentxs#591]
I followed all the steps found here (https://github.com/Open-Transactions/opentxs/blob/develop/docs/INSTALL-Debian_Ubuntu.txt), but the build fails while I'm using the cmake command:

> fatal: repository 'https://github.com/monetas/gtest.git/' not found
Clone of 'https://github.com/monetas/gtest.git' into submodule path 'deps/gtest' failed

**Comment by brenoc** [comment]
This error also occurs on the docker container.

**Comment by yamamushi** [comment]
This has been resolved, as the submodules were updated to point to opentxs/gtest.git instead of the monetas repository.
