### ISSUE TITLE
Error After updated

### ISSUE THREAD

**Issue by ychaim** [Open-Transactions/opentxs#599]
Hi Fellow .. I hope you are well ..

I got this issue after I did update my repo ..

Any suggestion  ?

Tks

Isssue
/root/opentxs/src/core/OTServerContract.cpp: In destructor ‘virtual opentxs::OTServerContract::~OTServerContract()’:
/root/opentxs/src/core/OTServerContract.cpp:81:63: error: useless cast to type ‘uint8_t* {aka unsigned char*}’ [-Werror=useless-cast]
         uint8_t * pKey = static_cast<uint8_t *>(m_transportKey);
                                                               ^
cc1plus: all warnings being treated as errors
src/core/CMakeFiles/opentxs-core.dir/build.make:1046: recipe for target 'src/core/CMakeFiles/opentxs-core.dir/OTServerContract.cpp.o' failed
make[2]: *** [src/core/CMakeFiles/opentxs-core.dir/OTServerContract.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/root/opentxs/build'
CMakeFiles/Makefile2:516: recipe for target 'src/core/CMakeFiles/opentxs-core.dir/all' failed
make[1]: *** [src/core/CMakeFiles/opentxs-core.dir/all] Error 2
make[1]: Leaving directory '/root/opentxs/build'
Makefile:150: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by csk1nner** [comment]
I'm getting the exact same error.  You get a resolution for this?

**Comment by yamamushi** [comment]
Could I get some information on what OS/Compiler versions you're using to build when you get this error?

I'll dig in and figure out where the issues are coming from if you can provide me that :-)

**Comment by csk1nner** [comment]
Of course!  Please let me know what else you need.

caleb@ubuntu14:~$ gcc --version
gcc (Ubuntu 4.9.2-0ubuntu1~14.04) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


caleb@ubuntu14:~$ sudo lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

**Comment by yamamushi** [comment]
Thanks! I'll take a look at this over the next day to try and get a resolution committed for you two.

In the meantime, there is a way to workaround it by adding the appropriate GCC diagnostic pragmas to the top of the source file throwing errors (OTServerContract.cpp in this case). 

The relevant documentation for GCC that will help you is: https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html , and the specific error you're trying to get GCC to ignore is "-Werror=useless-cast".

Although if you don't want to muck around with editing the source code to put pragmas in (who would?), you should be able to disable GCC's Werror's entirely with "export CXXFLAGS = "-Wno-error""

**Comment by csk1nner** [comment]
On it.  I'll chase this down tonight and then update this thread with the appropriate string to compile the bits down

**Comment by csk1nner** [comment]
I added the following to the opentxs/src/core/OTServerContract.cpp file:
--
#pragma GCC diagnostic warning "-Wuseless-cast"
--
This line was added right above the code that was causing the problem.  In this case it was line 81.  Adding "export CXXFLAGS="-Wno-error"" didn't work.  Most likely related to my inexperience with gcc.  Anyways got a build now.  It should be noted that this cast the compiler is complaining about is commented about in the code.

**Comment by lclc** [comment]
Well, that's not really a solution to the problem.

Since we don't have a CI anymore things get merged that don't build on different systems and with different compilers.
https://github.com/Open-Transactions/opentxs/commit/8a90754bf5ae09568b9484a8f1aa23a8a4a96e99#diff-e74ef3a5a33c5f6a0ed7fe24e973b0e3
Maybe this builds with clang..

Like the warning says, the cast to uint8_t isn't needed since uint8_t is already an unsigned char. So if you just remove the cast it should be good.

**Comment by csk1nner** [comment]
Hey mate,

I'm not familiar with the code of conduct for an open source project.  I've ran a dev shop for some time and make all the devs comment and check in their code.  If there's a continuing problem I deal with the dev.  This keeps the code in a good state.  How should this work in this space?  I completely agree with you that the fix I made doesn't really address the underlying issue.  With the vast number of possible OS and gcc versions to test how does one go about changing code?  Testing on one version of an Ubuntu server seems very lacking to me.  Is there an automated build process that this all goes through to verify that the change will not break some other OS/GCC?  

Just trying not to step on any toes here,

C

**Comment by lclc** [comment]
We used to have Jenkins as Continuous Integration, building OT and the notary on various operating systems and different compilers. But when Monetas decided not to use OT anymore they shut those down.

Before that we had Travis CI (travis-ci.org) which does that for free. You can find the .travis file back in the commit history of OT. It would probably still work after some adjustments. @yamamushi looked into it, I don't know the progress he made.

For serious development we'd need to have a CI again.

**Comment by yamamushi** [comment]
I agree that the fix isn't a permanent one, but seeing as how csk1nner was trying to build opentxs, I didn't want to make him wait all weekend for us to give him a permanent solution. The fix isn't harmful, and should have allowed him to test opentxs at least until we merge a better solution up.

In regards to CI, we are in the process of setting up a Jenkins build system, but it will be a few weeks before it's implemented if only because we are prioritizing several different issues amongst a very small group at the moment. 

If someone wants to take up the Travis CI system, that would be very much appreciated and we can forego setting up Jenkins. All that should be necessary is putting back the .travis file and making some fixes here and there to appease their build servers.

**Comment by yamamushi** [comment]
Sorry about the commit references, was having issues with my username on my fork.

**Comment by 11exa11** [comment]
I catch Make: ***[all] Error  too
different for make and make -j2
Ubuntu 16.04.5 LTS
Linux nelly 4.4.0-67-generic 

$ make 
..........
[ 25%] Building CXX object deps/opentxs-proto/src/verify/CMakeFiles/verify.dir/blockchaintransaction/BlockchainTransaction_1.cpp.o
cd /home/lexa/tmp-OT/opentxs/build/deps/opentxs-proto/src/verify && /usr/bin/c++   -DEXPORT="" -DOT_BUNDLED_LIBRESSL -DOT_LUCRE_DEBUG=0 -DOT_PREFIX_PATH=\"/usr/local\" -DOT_VALGRIND=0 -I/home/lexa/tmp-OT/opentxs/deps/opentxs-proto/include -I/home/lexa/tmp-OT/opentxs/deps/opentxs-proto/generated -isystem /home/lexa/tmp-OT/opentxs/build/deps/protobuf/install/include -I/home/lexa/tmp-OT/opentxs/build/include -isystem /home/lexa/tmp-OT/opentxs/build/deps/opentxs-proto/src  -std=c++17 -pthread -fPIC -std=c++17 -pthread -fPIC -Wall -Werror -Wextra -pedantic -Wno-missing-braces -Wcast-align -Wctor-dtor-privacy -Wdisabled-optimization -Winit-self -Wmissing-include-dirs -Wswitch-default -Wold-style-cast -Woverloaded-virtual -Wmissing-declarations -Wno-deprecated-declarations -Wno-unused-parameter -Wno-old-style-cast -Wunused-macros -Wundef -Wformat=2 -Wno-format-nonliteral -Wno-disabled-optimization -Wno-attributes -Wnoexcept -Wstrict-null-sentinel -Wlogical-op -O3 -DNDEBUG   -o CMakeFiles/verify.dir/blockchaintransaction/BlockchainTransaction_1.cpp.o -c /home/lexa/tmp-OT/opentxs/deps/opentxs-proto/src/verify/blockchaintransaction/BlockchainTransaction_1.cpp
/home/lexa/tmp-OT/opentxs/deps/opentxs-proto/src/verify/blockchaintransaction/BlockchainTransaction_1.cpp: In function ‘bool opentxs::proto::CheckProto_1(const opentxs::proto::BlockchainTransaction&, bool)’:
/home/lexa/tmp-OT/opentxs/deps/opentxs-proto/src/verify/blockchaintransaction/BlockchainTransaction_1.cpp:42:30: error: use of ‘input’ before deduction of ‘auto’
     for (const auto& input : input.input()) {
                              ^
deps/opentxs-proto/src/verify/CMakeFiles/verify.dir/build.make:473: recipe for target 'deps/opentxs-proto/src/verify/CMakeFiles/verify.dir/blockchaintransaction/BlockchainTransaction_1.cpp.o' failed
make[2]: *** [deps/opentxs-proto/src/verify/CMakeFiles/verify.dir/blockchaintransaction/BlockchainTransaction_1.cpp.o] Error 1
make[2]: Leaving directory '/home/lexa/tmp-OT/opentxs/build'
CMakeFiles/Makefile2:624: recipe for target 'deps/opentxs-proto/src/verify/CMakeFiles/verify.dir/all' failed
make[1]: *** [deps/opentxs-proto/src/verify/CMakeFiles/verify.dir/all] Error 2
make[1]: Leaving directory '/home/lexa/tmp-OT/opentxs/build'
Makefile:163: recipe for target 'all' failed
make: *** [all] Error 2

$ make -j2
.........
[  2%] Building CXX object src/storage/tree/CMakeFiles/opentxs-storage-tree.dir/Bip47Channels.cpp.o
cd /home/lexa/tmp-OT/opentxs/build/src/storage/tree && /usr/bin/c++   -DEXPORT="" -DOT_BUNDLED_LIBRESSL -DOT_LUCRE_DEBUG=0 -DOT_PREFIX_PATH=\"/usr/local\" -DOT_VALGRIND=0 -D_XOPEN_SOURCE=700 -I/home/lexa/tmp-OT/opentxs/deps/opentxs-proto/include -I/home/lexa/tmp-OT/opentxs/deps/opentxs-proto/generated -isystem /home/lexa/tmp-OT/opentxs/build/deps/protobuf/install/include -I/home/lexa/tmp-OT/opentxs/build/include -I/home/lexa/tmp-OT/opentxs/include -I/home/lexa/tmp-OT/opentxs/src  -std=c++17 -pthread -fPIC -Wall -Werror -Wextra -pedantic -Wno-missing-braces -Wcast-align -Wctor-dtor-privacy -Wdisabled-optimization -Winit-self -Wmissing-include-dirs -Wswitch-default -Wold-style-cast -Woverloaded-virtual -Wmissing-declarations -Wno-deprecated-declarations -Wno-unused-parameter -Wno-old-style-cast -Wunused-macros -Wundef -Wformat=2 -Wno-format-nonliteral -Wno-attributes -Wnoexcept -Wstrict-null-sentinel -Wlogical-op -Wno-parentheses -O3 -DNDEBUG -fPIC   -o CMakeFiles/opentxs-storage-tree.dir/Bip47Channels.cpp.o -c /home/lexa/tmp-OT/opentxs/src/storage/tree/Bip47Channels.cpp
In file included from /home/lexa/tmp-OT/opentxs/include/opentxs/Exclusive.hpp:9:0,
                 from /home/lexa/tmp-OT/opentxs/include/opentxs/Forward.hpp:11,
                 from /home/lexa/tmp-OT/opentxs/src/Internal.hpp:8,
                 from /home/lexa/tmp-OT/opentxs/src/storage/tree/Bip47Channels.hpp:41,
                 from /home/lexa/tmp-OT/opentxs/src/storage/tree/Bip47Channels.cpp:41:
/home/lexa/tmp-OT/opentxs/include/opentxs/Types.hpp:133:32: error: ‘shared_mutex’ is not a member of ‘std’
 using sLock = std::shared_lock<std::shared_mutex>;
...................
/home/lexa/tmp-OT/opentxs/src/storage/tree/Bip47Channels.cpp:379:1: error: expected ‘}’ at end of input
cc1plus: all warnings being treated as errors
src/storage/tree/CMakeFiles/opentxs-storage-tree.dir/build.make:65: recipe for target 'src/storage/tree/CMakeFiles/opentxs-storage-tree.dir/Accounts.cpp.o' failed
make[2]: *** [src/storage/tree/CMakeFiles/opentxs-storage-tree.dir/Accounts.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
src/storage/tree/CMakeFiles/opentxs-storage-tree.dir/build.make:89: recipe for target 'src/storage/tree/CMakeFiles/opentxs-storage-tree.dir/Bip47Channels.cpp.o' failed
make[2]: *** [src/storage/tree/CMakeFiles/opentxs-storage-tree.dir/Bip47Channels.cpp.o] Error 1
make[2]: Leaving directory '/home/lexa/tmp-OT/opentxs/build'
CMakeFiles/Makefile2:989: recipe for target 'src/storage/tree/CMakeFiles/opentxs-storage-tree.dir/all' failed
make[1]: *** [src/storage/tree/CMakeFiles/opentxs-storage-tree.dir/all] Error 2
make[1]: Leaving directory '/home/lexa/tmp-OT/opentxs/build'
Makefile:163: recipe for target 'all' failed
make: *** [all] Error 2
