### ISSUE TITLE
Mac Install build/install instructions leaves zeromq without sodium

### ISSUE THREAD

**Issue by jgostylo** [Open-Transactions/opentxs#611]
The OSX with homebrew instructions say to install zeromq like this:
brew install --cc=clang --with-sodium zeromq

When I get around to building and running Moneychanger I get this error when Creating an Account:
Error: libzmq has no libsodium support

I believe I read that zeromq installations where --with-sodium is used will generate a warning when sodium is not present but will still build.  My current state of uninstalling zeromq and installing it again does not show a warning so I am not certain this is the case.

**Comment by yamamushi** [comment]
Try these directions (I'm including the openssl ones as those may cause you issues later too):

# Open-Transactions (opentxs) requires openssl-1.0.0 or greater, so we will need to install a newer version to accomodate it

$ brew tap homebrew/versions
$ brew tap homebrew/boneyard
$ cd /usr/local/Library/Formula/
$ git checkout d915ce8
$ cd -
$ brew switch openssl 1.0.1h
$ brew install openssl
$ brew link --force openssl

# install libsodium from brew
$ brew install --universal libsodium

# There have been compatibility issues using zeromq that comes through homebrew
# It is therefore recommended to install and use libzmq from the deps directory inside of the
# opentxs project.
