### ISSUE TITLE
Extend Trezor crypto wrapper to provide secp256k1 functionality

### ISSUE THREAD

**Issue by justusranvier** [Open-Transactions/opentxs#703]
Depends on: #702 
- Implement required methods and make opentxs::TrezorCrypto a child class of opentxs::Secp256k1
- Create new defines SECP256K1_VIA_LIBSECP256K1 and SECP256K1_VIA_TREZOR and associated CMake options
- Add appropriate logic to use the specified implementation based on the CMake options

**Comment by cppcoin** [comment]
вы мне можите помочь?не разбирусь ни как(
